#!/bin/sh
#
# Install dependencies.

set -e

# Go to the root directory of the project.
cd "$(dirname $0)"/..

# Check that ``bundler`` is installed
(gem list -i bundler >/dev/null) || {
  printf "%s\n" $'
Bundler (a prerequisite) was not found. To install Bundler:

1. Update Ruby gem: gem update --system
2. Install Bundler: gem install bundler
3. Reload your shell
4. Check that the Bundler CLI executable is installed: which bundle
'
exit 1
}

# Remove old files.
rm -f .bundle/config

# Install dependencies.
bundle check --path .bundle >/dev/null 2>&1 ||
  bundle install --binstubs=bin --path=.bundle

echo "==> Dependencies installed"
