#!/bin/sh
#
# Build and deploy website to remote host.

set -e

cd "$(dirname $0)"/..

# Install dependencies
script/bootstrap

# Build site
#bundle exec bin/jekyll build --config _config.yml,_config-production.yml
bundle exec bin/jekyll build --config _config.yml
